x: # Theme specific stuff
  author: Ashutosh Gangwar
  description: Personal thoughts, opinions and experiences.
  social:
    - name: github
      # prefix: github.com ## default is '{name}.com'
      username: ashutoshgngwr
    - name: twitter
      username: ashutoshgngwr
  goatcounter: https://ashutoshgngwr.goatcounter.com/count

plugins:
  - jekyll-mentions
  - jekyll-redirect-from

show_drafts: true
collections:
  pages:
    output: true
    permalink: /:title
    sitemap_priority: 0.9
  posts:
    output: true
    permalink: /:title
    sitemap_priority: 0.8
  drafts:
    output: true
    permalink: /:title
    sitemap_priority: 0.7
  icons:
    output: false
  noice: # Config for redirecting links to the new Noice portal
    output: true
    permalink: /:collection/:path
    sitemap_priority: 1.0

defaults:
  - scope:
      path: ""
    values:
      layout: page

# compress output content
sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: []
  startings: []
  ignore:
    envs: ["development"]

# disable Jekyll's syntax highlighting
# https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#syntax-highlighting
kramdown:
  syntax_highlighter_opts:
    disable: true

jekyll-mentions:
  base_url: https://twitter.com

exclude:
  - "vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE"
